import Head from "next/head";
import Message from "../components/Message";
import { useState, useEffect } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, query, orderBy } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });

    return unsubscribe;
  };

  useEffect(() => getPosts, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2 className="text-2xl">See what other people are saying</h2>
        {allPosts && allPosts.map((post) => (
          <Message {...post} key={post.id}>
              <Link href={{ pathname: `/${post.id}`, query: {...post} }}>
                <button className="text-sm text-cyan-500">{post.comments?.length} comments</button>
              </Link>
          </Message>
        ))}
      </div>
    </>
  );
}
